server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirigir llamadas de API al backend correspondiente
    location /api/ventas/ {
        proxy_pass http://backend-ventas:8082/;
    }

    location /api/despachos/ {
        proxy_pass http://backend-despachos:8081/;
    }
}