apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: backend-ventas
        image: devops-back-ventas:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_ENDPOINT
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "db_ventas"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas-service
spec:
  type: ClusterIP
  selector:
    app: backend-ventas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-ventas-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-ventas-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60