name: Continuous Deployment a EKS

on:
  push:
    branches:
      - main # Se ejecuta automáticamente al hacer commit en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    # 1. Autenticación en AWS (Importante: incluye el token de sesión por ser AWS Academy)
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: us-east-1

    # 2. Login en el registro de contenedores (ECR)
    - name: Login a Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 3. Build y Push: Frontend
    - name: Build, tag, y push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/devops-frontend:$IMAGE_TAG ./front_despacho
        docker push $ECR_REGISTRY/devops-frontend:$IMAGE_TAG

    # 4. Build y Push: Backend Despachos
    - name: Build, tag, y push Backend Despachos
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/devops-back-despachos:$IMAGE_TAG ./backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push $ECR_REGISTRY/devops-back-despachos:$IMAGE_TAG

    # 5. Build y Push: Backend Ventas
    # 5. Build y Push: Backend Ventas
    - name: Build, tag, y push Backend Ventas
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/devops-back-ventas:$IMAGE_TAG ./backend/back-Ventas_SpringBoot/Springboot-API-REST
        docker push $ECR_REGISTRY/devops-back-ventas:$IMAGE_TAG

    # 6. Conectar GitHub con tu clúster de Kubernetes
    - name: Actualizar Kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name devops3-cluster

    # 7. Despliegue en EKS
    - name: Deploy a Kubernetes
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Aplica los manifiestos base
        kubectl apply -f infra/k8s/
        
        # Fuerza la actualización de las imágenes a la versión del commit actual
        kubectl set image deployment/frontend-deployment frontend=$ECR_REGISTRY/devops-frontend:$IMAGE_TAG
        kubectl set image deployment/backend-despachos-deployment backend-despachos=$ECR_REGISTRY/devops-back-despachos:$IMAGE_TAG
        kubectl set image deployment/backend-ventas-deployment backend-ventas=$ECR_REGISTRY/devops-back-ventas:$IMAGE_TAG